services:
  web:
    build: .
    ports:
      - "5004:5004"
    volumes:
      # Mount the local prompts directory to the location the app expects
      - ./prompts:/usr/src/app/prompts
      # Mount the application code for live reloading
      - ./app:/usr/src/app/app
      # Persist data outside the container
      - ./app_data:/usr/src/app/data
    env_file:
      - .env
    # To make the container interactive and see print statements
    tty: true
    stdin_open: true
