name: Dependabot Automerge
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Wait for status checks
        id: wait_for_checks
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'lint' # The name of the job in ci.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Automerge Dependabot PR
        if: steps.wait_for_checks.outputs.conclusion == 'success'
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
